/* eslint-disable camelcase */
// Generated by https://quicktype.io

export interface PackageAPIResponse {
  id: string;
  object: string;
  mode: string;
  tracking_code: string;
  status: string;
  created_at: string;
  updated_at: string;
  signed_by: null;
  weight: null;
  est_delivery_date: string;
  shipment_id: null;
  carrier: string;
  public_url: string;
  tracking_details: TrackingDetail[];
  carrier_detail: null;
  fees: Fee[];
}

export interface Fee {
  object: string;
  type: string;
  amount: string;
  charged: boolean;
  refunded: boolean;
}

export interface TrackingDetail {
  object: string;
  message: string;
  status: string;
  datetime: string;
  source: string;
  tracking_location: TrackingLocation;
}

export interface TrackingLocation {
  object: string;
  city: string;
  state: string;
  country: null;
  zip: string;
}
